### ISSUE TITLE
Add in dijkstra's_algo to Algorithms Hub

### ISSUE THREAD

**Issue by SubhayanDas08** [MSCKIIT/Small-Projects#105]
#Proposed Change

Add in the mentioned algorithm to Algorithms Hub in its respective folder. 

**Read the CONTRIBUTING.md of Algorithms Hub before contributing**

#Languages that can be used to write the algorithm:
* [x] C++ or C
* [x] Javascript
* [x] Python
* [x] Java
* [x] Golang
* [x] Ruby
* [x] C#

**Comment by shreya0204** [comment]
Please Assign this to me

**Comment by MaiShantanuHu** [comment]
Please assign me this task I can do it in java!

**Comment by ash8879** [comment]
can u please assign this to me I can add code for all languages.

**Comment by divyansh1511** [comment]
can u please assign this to me...I can code in cpp.

**Comment by ayush523** [comment]
Hi.I have coded it in python.

**Comment by divyansh1511** [comment]
@nishant-giri I made the PR (i.e #214) you can merge the PR.

**Comment by Sidd1121** [comment]
I am a beginner open source enthusiast, please consider me for future issues
