### ISSUE TITLE
Add Code for 7 Segment Display

### ISSUE THREAD

**Issue by nishant-giri** [MSCKIIT/Small-Projects#189]
## Changes Required
Add code for 7 Segment Display in Java or Python.
Refer to the C++ code and README.md of 7 Segment Display before contributing.

## Programming Language
* [x] Java
* [x] Python

**Comment by sumitkumarju** [comment]
Hey, i can work on this issue.Please assign it to me

**Comment by nishant-giri** [comment]
@sumitkumarju, I've assigned you the task.
