### ISSUE TITLE
Add in bucketsort to Algorithms Hub

### ISSUE THREAD

**Issue by SubhayanDas08** [MSCKIIT/Small-Projects#90]
#Proposed Change

Add in the mentioned algorithm to Algorithms Hub in its respective folder. 

**Read the CONTRIBUTING.md of Algorithms Hub before contributing**

#Languages that can be used to write the algorithm:
* [x] C++ or C
* [x] Javascript
* [x] Python
* [x] Java
* [x] Golang
* [x] Ruby
* [x] C#

**Comment by nishant-giri** [comment]
Kindly assign me this issue.

**Comment by nishant-giri** [comment]
Kindly assign me this task.

**Comment by nishant-giri** [comment]
Added code for Bucket Sort algorithm in C.

**Comment by ash8879** [comment]
Can u please assign me this task I can write this code in all language.

**Comment by adisin361** [comment]
Kindly assign this task to me @SubhayanDas08

**Comment by Geek-Tekina** [comment]
Can you assign me this task , i will code in cpp.
