### ISSUE TITLE
Add in pigeonholeSort to Algorithms Hub

### ISSUE THREAD

**Issue by SubhayanDas08** [MSCKIIT/Small-Projects#97]
#Proposed Change

Add in the mentioned algorithm to Algorithms Hub in its respective folder. 

**Read the CONTRIBUTING.md of Algorithms Hub before contributing**

#Languages that can be used to write the algorithm:
* [x] C++ or C
* [x] Javascript
* [x] Python
* [x] Java
* [x] Golang
* [x] Ruby
* [x] C#

**Comment by nishant-giri** [comment]
Kindly assign me this issue.

**Comment by ash8879** [comment]
can u please assign this to me I can add code for all languages.

**Comment by nishant-giri** [comment]
@ash8879, I've assigned you the task. Try uploading the codes for the algorithm in the mentioned languages except C++.

**Comment by sharonibose** [comment]
Kindly assign me this task in c
